version: '3.1'

services:

  mongo:
    image: mongo:5.0.5
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - servicenet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - servicenet
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      
  machine-metrics:
      build:
         context: ./
         dockerfile: Dockerfile
         args:
            JAR_FILE: speed-metrics-0.0.1.jar
      ports:
      - 80:8080
      networks:
      - servicenet
      environment:
      - DB_HOST=mongo
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_AUTH_DB=${DB_AUTH_DB}
      depends_on:
      - mongo
  
networks:
   servicenet: null